id = "solidity"
name = "Solidity"
version = "0.2.0"
schema_version = 1
authors = [
    "Daniel Zarifpour <z@rifpour.xyz> (Original Creator)",
    "Jacob Czepluch <j.czepluch@proton.me> (Current Maintainer)",
]
description = "Zed extension for the Solidity language"
repository = "https://github.com/czepluch/zed-solidity"

languages = ["solidity"]

[language_servers.solidity]
name = "Solidity Language Server"
languages = ["Solidity"]
language_ids = { "Solidity" = "solidity" }

[grammars.solidity]
repository = "https://github.com/JoranHonig/tree-sitter-solidity"
rev = "4e938a46c7030dd001bc99e1ac0f0c750ac98254"
