id = "solidity"
name = "Solidity"
version = "0.1.4"
schema_version = 1
authors = ["Daniel Zarifpour <z@rifpour.xyz>"]
description = "💠 Solidity language support for Zed. ✰ and report issues ➩"
repository = "https://github.com/zarifpour/zed-solidity"

languages = ["solidity"]

[language_servers.solidity-language-server]
name = "Solidity Language Server"
languages = ["solidity"]
language_ids = { "solidity" = "solidity" }

[grammars.solidity]
repository = "https://github.com/JoranHonig/tree-sitter-solidity"
rev = "4e938a46c7030dd001bc99e1ac0f0c750ac98254"
